name: Build with CMakePresets.json but do not run because Github Action cannot stop the GUI

on:
  push: 
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

env:
  SDL_VERSION: 2.28.5
  
jobs:
  singleConfig:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        preset:
        # single config generators
          - Ninja-Msvc-Debug
          - Ninja-Msvc-Release
          - Ninja-Gnu-Debug
          - Ninja-Gnu-Release
          - Ninja-Clang-Debug
          - Ninja-Clang-Release
          - NMake-Msvc-Debug
          - NMake-Msvc-Release
          - Make-Gnu-Debug
          - Make-Gnu-Release
          - Make-Clang-Debug
          - Make-Clang-Release

        exclude:
        # Ubuntu doesn't have MSVC compiler
          - os: ubuntu-latest
            preset: Ninja-Msvc-Debug
          - os: ubuntu-latest
            preset: Ninja-Msvc-Release
          - os: ubuntu-latest
            preset: NMake-Msvc-Debug
          - os: ubuntu-latest
            preset: NMake-Msvc-Release

        # MacOS doesn't have MSVC compiler nor the GNU C++ compiler 
        # (actually its g++ is an alias for clang++)
          - os: macos-latest
            preset: Ninja-Gnu-Debug
          - os: macos-latest
            preset: Ninja-Gnu-Release
          - os: macos-latest
            preset: Ninja-Msvc-Debug
          - os: macos-latest
            preset: Ninja-Msvc-Release
          - os: macos-latest
            preset: NMake-Msvc-Debug
          - os: macos-latest
            preset: NMake-Msvc-Release
          - os: macos-latest
            preset: NMake-Gnu-Debug
          - os: macos-latest
            preset: NMake-Gnu-Release

        # Windows doesn't have GNU nor Clang compilers
          - os: windows-latest
            preset: Ninja-Gnu-Debug
          - os: windows-latest
            preset: Ninja-Gnu-Release
          - os: windows-latest
            preset: Ninja-Clang-Debug
          - os: windows-latest
            preset: Ninja-Clang-Release
          - os: windows-latest
            preset: Make-Gnu-Debug
          - os: windows-latest
            preset: Make-Gnu-Release
          - os: windows-latest
            preset: Make-Clang-Debug
          - os: windows-latest
            preset: Make-Clang-Release
        
    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install MSVC compiler
      if: ${{matrix.os == 'windows-latest'}}
      uses: ilammy/msvc-dev-cmd@v1
        
    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

# Do not cache SDL2 on Linux because it is tied to too many dependencies which would also need to be cached 

    - name: Cache SDL2 on Mac (if not yet cached) or else restore it from cache (if cached already)
      if: ${{matrix.os == 'macos-latest'}}
      id: mac-SDL2-ID-installed-cache
      uses: actions/cache@v3
      with:
        path: /usr/local/Cellar/sdl2
        key: mac-SDL2-KEY-installed-cache

    - name: Cache SDL2 on Windows (if not yet cached) or else restore it from cache (if cached already)
      if: ${{matrix.os == 'windows-latest'}}
      id: windows-SDL2-ID-installed-cache
      uses: actions/cache@v3
      with:
        path: C:\SDL2
        key: windows-SDL2-KEY-installed-cache

    - name: Install SDL2 on Linux/Mac if it is not yet cached
      if: ${{matrix.os != 'windows-latest'}}
      shell: bash
      run: |
        if [[ ${{matrix.os == 'ubuntu-latest'}} == "true" ]]; then
      # &&
      # steps.windows-SDL2-ID-installed-cache.outputs.cache-hit != 'true'
          echo sudo apt-get install libsdl2-dev
          sudo apt-get install libsdl2-dev

          echo find /usr/include/SDL2 -iname SDL.h
          find /usr/include/SDL2 -iname SDL.h
          echo find /usr/lib/x86_64-linux-gnu -iname libSDL2.a
          find /usr/lib/x86_64-linux-gnu -iname libSDL2.a
          echo find /usr/lib/x86_64-linux-gnu -iname libSDL2.so
          find /usr/lib/x86_64-linux-gnu -iname libSDL2.so
          echo find /usr/lib/x86_64-linux-gnu/cmake/SDL2 -iname SDL2?Config.cmake
          find /usr/lib/x86_64-linux-gnu/cmake/SDL2 -iname SDL2?Config.cmake
          
          echo ls /usr/include/SDL2
          ls /usr/include/SDL2
          echo ls /usr/lib/x86_64-linux-gnu
          ls /usr/lib/x86_64-linux-gnu
          echo ls /usr/lib/x86_64-linux-gnu/cmake/SDL2
          ls /usr/lib/x86_64-linux-gnu/cmake/SDL2

        elif [[ ${{matrix.os == 'macos-latest'}} == "true" ]]; then
          echo brew install sdl2
          brew install sdl2

          find /usr/local/Cellar/sdl2 -iname SDL.h
          find /usr/local/Cellar/sdl2 -iname libSDL2.a
          find /usr/local/Cellar/sdl2 -iname libSDL2.so
          find /usr/local/Cellar/sdl2 -iname SDL2?Config.cmake
          
          echo ls /usr/local/Cellar/sdl2/2.28.5/include/SDL2
          ls /usr/local/Cellar/sdl2/2.28.5/include/SDL2
          echo ls /usr/local/Cellar/sdl2/2.28.5/lib
          ls /usr/local/Cellar/sdl2/2.28.5/lib
          echo ls /usr/local/Cellar/sdl2/2.28.5/lib/cmake/SDL2
          ls /usr/local/Cellar/sdl2/2.28.5/lib/cmake/SDL2
        fi

    - name: Install SDL2 on Windows if it is not yet cached
      if: ${{matrix.os == 'windows-latest'}}
      run: |
        Invoke-WebRequest "https://github.com/libsdl-org/SDL/releases/download/release-$env:SDL_VERSION/SDL2-devel-$env:SDL_VERSION-VC.zip" -o C:\SDL.zip
        Expand-Archive C:\SDL.zip -DestinationPath C:\SDL2
        
        Write-Host ls C:\SDL2 -Include SDL.h -Recurse -Name
        ls C:\SDL2 -Include SDL.h -Recurse -Name
        Write-Host ls C:\SDL2 -Include SDL2.lib -Recurse -Name
        ls C:\SDL2 -Include SDL2.lib -Recurse -Name
        Write-Host ls C:\SDL2 -Include SDL2.dll -Recurse -Name
        ls C:\SDL2 -Include SDL2.dll -Recurse -Name
        Write-Host ls C:\SDL2 -Include SDL2?Config.cmake -Recurse -Name
        ls C:\SDL2 -Include SDL2?Config.cmake -Recurse -Name

        Write-Host ls C:\SDL2\SDL2-2.28.5\include -Name
        ls C:\SDL2\SDL2-2.28.5\include -Name
        Write-Host ls C:\SDL2\SDL2-2.28.5\lib\x86 -Name
        ls C:\SDL2\SDL2-2.28.5\lib\x86 -Name
        Write-Host ls C:\SDL2\SDL2-2.28.5\lib\x64 -Name
        ls C:\SDL2\SDL2-2.28.5\lib\x64 -Name
        Write-Host ls C:\SDL2\SDL2-2.28.5\cmake -Name
        ls C:\SDL2\SDL2-2.28.5\cmake -Name

    - name: Tool versions
      shell: bash
      run: |
        if [[ ${{matrix.os == 'windows-latest'}} == "true" ]]; then
          echo cl
          cl
          echo
        fi
        echo g++ --version
        g++ --version
        echo 
        echo clang++ --version
        clang++ --version
        echo 
        echo cmake --version
        cmake --version
        echo 
        echo ninja --version
        ninja --version

    - name: Parameter values
      shell: bash
      run: | 
        echo platform = ${{runner.os}}
        echo preset = ${{matrix.preset}}

    - name: CMake configure
      run: cmake --preset ${{matrix.preset}}
      
    - name: CMake build
      run: cmake --build --preset ${{matrix.preset}}

#====================
# Comment out because Github Action will launch the GUI but will not be able to stop it
# so it would run indefinitely, and there is no way to interact with the GUI anyway.
#====================
    # - name: CMake run program
    #   run: cmake --build --preset ${{matrix.preset}} --target run


  multiConfig:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        preset:
        # multi config generators
          - NinjaMC-Msvc
          - NinjaMC-Gnu
          - NinjaMC-Clang
          - VSx32-Msvc
          - VSx64-Msvc
          - Xcode-Clang
        build_type: [Debug, Release]

        exclude:
          - os: ubuntu-latest
            preset: NinjaMC-Msvc
          - os: ubuntu-latest
            preset: VSx32-Msvc
          - os: ubuntu-latest
            preset: VSx64-Msvc
          - os: ubuntu-latest
            preset: Xcode-Clang
            
          - os: macos-latest
            preset: NinjaMC-Gnu
          - os: macos-latest
            preset: NinjaMC-Msvc
          - os: macos-latest
            preset: NMake-Msvc
          - os: macos-latest
            preset: Make-Gnu
          - os: macos-latest
            preset: VSx32-Msvc
          - os: macos-latest
            preset: VSx64-Msvc

          - os: windows-latest
            preset: NinjaMC-Gnu
          - os: windows-latest
            preset: NinjaMC-Clang
          - os: windows-latest
            preset: Make-Gnu
          - os: windows-latest
            preset: Make-Clang
          - os: windows-latest
            preset: Xcode-Clang
        
    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install MSVC compiler
      if: ${{matrix.os == 'windows-latest'}}
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Install SDL2 (Linux/Mac)
      if: ${{matrix.os != 'windows-latest'}}
      shell: bash
      run: |
        if [[ ${{matrix.os == 'ubuntu-latest'}} == "true" ]]; then
          echo sudo apt-get install libsdl2-dev
          sudo apt-get install libsdl2-dev
          echo 
          find /usr -iname SDL.h
          find /usr -iname libSDL2.a
          find /usr -iname libSDL2.so
          find /usr -iname SDL2?Config.cmake
        elif [[ ${{matrix.os == 'macos-latest'}} == "true" ]]; then
          echo brew install sdl2
          brew install sdl2
          echo 
          find /usr/local/Cellar/sdl2 -iname SDL.h
          find /usr/local/Cellar/sdl2 -iname libSDL2.a
          find /usr/local/Cellar/sdl2 -iname libSDL2.so
          find /usr/local/Cellar/sdl2 -iname SDL2?Config.cmake
        fi

    - name: Install SDL2 (Windows)
      if: ${{matrix.os == 'windows-latest'}}
      run: |
        Invoke-WebRequest "https://github.com/libsdl-org/SDL/releases/download/release-$env:SDL_VERSION/SDL2-devel-$env:SDL_VERSION-VC.zip" -o C:\SDL.zip
        Expand-Archive C:\SDL.zip -DestinationPath C:\SDL2
        Write-Host ""
        ls C:\SDL2 -Include SDL.h -Recurse -Name
        ls C:\SDL2 -Include SDL2.lib -Recurse -Name
        ls C:\SDL2 -Include SDL2.dll -Recurse -Name
        ls C:\SDL2 -Include SDL2?Config.cmake -Recurse -Name
        
    - name: Tool versions
      shell: bash
      run: |
        if [[ ${{matrix.os == 'windows-latest'}} == "true" ]]; then
          echo cl
          cl
          echo
        fi
        echo g++ --version
        g++ --version
        echo 
        echo clang++ --version
        clang++ --version
        echo 
        echo cmake --version
        cmake --version
        echo 
        echo ninja --version
        ninja --version

    - name: Parameter values
      shell: bash
      run: | 
        echo platform = ${{runner.os}}
        echo preset = ${{matrix.preset}}

    - name: CMake configure
      run: cmake --preset ${{matrix.preset}}
      
    - name: CMake build
      run: cmake --build --preset ${{matrix.preset}} --config ${{matrix.build_type}}

#====================
# Comment out because Github Action will launch the GUI but will not be able to stop it
# so it would run indefinitely, and there is no way to interact with the GUI anyway.
#====================
    # - name: CMake run program
    #   run: cmake --build --preset ${{matrix.preset}} --config ${{matrix.build_type}} --target run
